/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tahmin;

import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kerem
 */
public class tahminGUI extends javax.swing.JFrame {

    /**
     * Creates new form tahminGUI
     */
    public tahminGUI() {
        initComponents();
            tahmin=rand.nextInt(100);
         System.out.println(tahmin);
         tableModel = (DefaultTableModel) tabloTbl.getModel();
      
      
    }
    public void tabloUpdate(){
         DefaultTableModel clearModel = (DefaultTableModel) tabloTbl.getModel();//Güncellemede tekrar aynı liste üzerine eklemesin diye tablomuzun içini siliyoruz
        clearModel.setRowCount(0);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        girilenSayiLbl = new javax.swing.JLabel();
        girilenSayiTxt = new javax.swing.JTextField();
        canLbl = new javax.swing.JLabel();
        canTxt = new javax.swing.JTextField();
        UyarılarLbl = new javax.swing.JLabel();
        bilgiTxt = new javax.swing.JTextField();
        tahminSayiLbl = new javax.swing.JLabel();
        tahminSayiTxt = new javax.swing.JTextField();
        tahminEtBtn = new javax.swing.JButton();
        hosgeldinizLbl = new javax.swing.JLabel();
        bayrakLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabloTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        girilenSayiLbl.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        girilenSayiLbl.setText("Sayı Tahmininizi Yazınız");

        girilenSayiTxt.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        canLbl.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        canLbl.setText("Kalan Canınız");

        canTxt.setEditable(false);
        canTxt.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        UyarılarLbl.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        UyarılarLbl.setText("BİLGİLENDİRME !");

        bilgiTxt.setEditable(false);
        bilgiTxt.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        tahminSayiLbl.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        tahminSayiLbl.setText("Tutulan Sayı");

        tahminSayiTxt.setEditable(false);
        tahminSayiTxt.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        tahminEtBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        tahminEtBtn.setText("TAHMİN ET");
        tahminEtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahminEtBtnActionPerformed(evt);
            }
        });

        hosgeldinizLbl.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        hosgeldinizLbl.setText("HOŞGELDİN ! AKLIMDAN BİR SAYI TUTTUM BAKALIM BU SAYIYI TAHMİN EDEBİLECEK MİSİN?");

        bayrakLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tahmin/280318.jpg"))); // NOI18N

        tabloTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tahminleriniz"
            }
        ));
        jScrollPane1.setViewportView(tabloTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hosgeldinizLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UyarılarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(girilenSayiLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(girilenSayiTxt))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(canTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(canLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tahminSayiLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tahminSayiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tahminEtBtn)
                                .addGap(15, 15, 15))))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bilgiTxt))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(bayrakLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bayrakLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hosgeldinizLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(girilenSayiLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tahminSayiLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(girilenSayiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tahminSayiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tahminEtBtn))
                .addGap(18, 18, 18)
                .addComponent(UyarılarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bilgiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tahminEtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahminEtBtnActionPerformed
      
       
       
       String tahminTxt=Integer.toString(tahmin);
       
       if(girilenSayiTxt.getText().equals("")){
           JOptionPane.showMessageDialog(null, "Lütfen SAYI TAHMİNİNİZ Kutucuğuna Bir Değer Giriniz","DİKKAT !",JOptionPane.WARNING_MESSAGE);
      
       }
       else{
           sayi=Integer.parseInt(girilenSayiTxt.getText());
           if(sayi<0||sayi>99){
              JOptionPane.showMessageDialog(null,"Lütfen 0-99 Arası Bir Sayı Giriniz","Dikkat !",JOptionPane.WARNING_MESSAGE);
        
           }
       
           else{
               
      
             tableModel.insertRow(tableModel.getRowCount(), new Object[]{girilenSayiTxt.getText()});
             
                if(girilenSayiTxt.getText().equals(tahminTxt)&&can>0){
                    
                  bilgiTxt.setText("Tebrikler Sayıyı Tahmin Ettiniz !");        
                canTxt.setText(Integer.toString(can));
                tahminSayiTxt.setText(Integer.toString(tahmin));
            tahminEtBtn.removeNotify();
                
                     
      }
               }
           
         if(!girilenSayiTxt.getText().equals(tahminTxt)&&can>0){
          --can;
          bilgiTxt.setText("Bilemediniz tekrar Deneyiniz Kalan Hakkınız = " + can);
          canTxt.setText(Integer.toString(can));
         
          }
         if(can==0&&!girilenSayiTxt.getText().equals(tahminTxt)){
          bilgiTxt.setText("Oyun Bitti Maalesef Sayıyı Doğru Tahmin Edemediniz");
          tahminSayiTxt.setText(Integer.toString(tahmin));
           tahminEtBtn.removeNotify();
         }
                
         
       }
    
       
           
              
              
              
      
          
       
              
    }//GEN-LAST:event_tahminEtBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tahminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tahminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tahminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tahminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tahminGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UyarılarLbl;
    private javax.swing.JLabel bayrakLbl;
    private javax.swing.JTextField bilgiTxt;
    private javax.swing.JLabel canLbl;
    private javax.swing.JTextField canTxt;
    private javax.swing.JLabel girilenSayiLbl;
    private javax.swing.JTextField girilenSayiTxt;
    private javax.swing.JLabel hosgeldinizLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabloTbl;
    private javax.swing.JButton tahminEtBtn;
    private javax.swing.JLabel tahminSayiLbl;
    private javax.swing.JTextField tahminSayiTxt;
    // End of variables declaration//GEN-END:variables
Random rand=new Random();
public int sayi,tahmin,can=5,i=0;
 int[] tahminler =new int[6];
    DefaultTableModel tableModel;
    Object[] tableData;
}
